---
abstract: 'automate launching of fake mdp for testing purposes'
author:
  - 'Jerome Quelin'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Corpus-Audio-MPD
provides:
  Test::Corpus::Audio::MPD:
    file: lib/Test/Corpus/Audio/MPD.pm
    version: 1.100500
requires:
  English: 0
  Exporter: 0
  File::Copy: 0
  File::ShareDir: 0
  File::Temp: 0
  Module::Build: 0.3601
  Path::Class: 0
  Readonly: 0
  Test::More: 0
  perl: 5.008
resources:
  MailingList: http://groups.google.com/group/audio-mpd
  homepage: http://search.cpan.org/dist/Test-Corpus-Audio-MPD
  repository: http://github.com/jquelin/audio-mpd
version: 1.100500
